version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Python
          command: |
            sudo apt-get update
            sudo apt-get install python3
            sudo apt-get install python3-pip
      - run:
          name: Setup Versioning
          command: |
            pip3 install shyaml
            export VERSION="$(cat info.yml | shyaml get-value version)"
      - run:
          name: Build and Push application Docker image
          command: |
            echo "VERSION IS"
            echo "========="
            echo $VERSION
            echo "========="
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/circleci-docker-example:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/circleci-docker-example:$TAG