version: 3 # pls no touch this
debug: false
settings:
  name: 'Person' # Main name
  subtitle: 'Some for info' # A little text below namwe
  font: Roboto, Arial # The font-family to use for the page
  color: '#6F6F6F' # The color of the name and subtitle
  link-color: '#F6F6F6' # The color of the text on the links
  glass-card: true # If the image, name, subtitle and links should be displayed on a glass-like card
  background: # The background info
    type: color # image or color Decides what to put as the background
    content: '#2F2F2F' # url to image or a color code (e.g. /static/bg.png)
  favicon: /static/favicon.png # If you want a favicon
  description: Some info in the meta description tag # If you want a meta description
  image:
    type: font-awesome # image or font-awesome decides how to display avatar
    style: solid # for font-awesome. Decides what style to display the icon
    content: user # font-awesome icon name, or url to image
  links:
    - name: Google # Frienly Name of link
      link: https://google.com # The link to the link
      image: # same as the 'image' item above
        type: font-awesome
        style: brands
        content: google
      color: '#454FBF' # the background color of the link
    - name: Skarf Github # same as item above
      link: https://github.com/woooferz/skarf
      image:
        type: font-awesome
        style: brands
        content: github
      color: '#3F3F3F'

    