name: Docker V2

on:
  push: 
    branches: ['master', 'dev']
      

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: skarf
          tags: ${{ steps.extract_branch.outputs.branch }}
          archs: amd64, arm64
          dockerfiles: |
            ./Dockerfile
            
      - name: Push To DockerHub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/wooferz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push To DockerHub
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/woooferz
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Print image url
      #  run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
